### ISSUE TITLE
AttributeError: 'list' object has no attribute 'readlines'

### ISSUE THREAD

**Issue by dregad** [shello/gfs.py#1]
Hello,

Your script works fine if I pipe my list of dates into it, but I'm facing an error when using the `--file` argument.

```
$ ./gfs.py daily=3 --file /tmp/list
Traceback (most recent call last):
  File ".../gfs.py", line 504, in <module>
    main()
  File ".../gfs.py", line 478, in main
    dates = set(line.strip() for line in args.file.readlines())
                                         ^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'readlines'
```

Might be caused by use of `nargs=1` in the argument's declaration
https://github.com/shello/gfs.py/blob/02b9a1e1a632fa1069182a741ae983aa2ded7450/gfs.py#L458-L459

From the docs https://docs.python.org/3/library/argparse.html#nargs
> Note that **nargs=1 produces a list of one item**. This is different from the default, in which the item is produced by itself.

**Comment by shello** [comment]
Hey @dregad, thanks for reporting that issue. You're entirely correct that the `nargs=1` option shouldn't be there and is the root cause of this problem. I've pushed a commit to fix it.

```
% python3 gfs.py daily=3 </tmp/test_gfspy 
2017-05-21T22:00:00
2017-05-20T20:00:00
2017-05-14T19:00:00
% python3 gfs.py -f /tmp/test_gfspy daily=3
2017-05-14T19:00:00
2017-05-20T20:00:00
2017-05-21T22:00:00
```
